# Core flows across every module. Runs after test_auth.py in a shared namespace (see run.py).
topics=call('GET','/topics')['data']; T=[t['id'] for t in topics]
ada, ada_id = signup('Ada Obi','ada@example.com')
tunde, tunde_id = signup('Tunde Bello','tunde@example.com')
chi, chi_id = signup('Chioma Eze','chioma@example.com')
call('POST','/posts',ada,{'body':'hi'},expect=403)  # onboarding required
for tok,role in [(ada,'innovator'),(tunde,'researcher'),(chi,'expert')]:
    call('PATCH','/me/onboarding',tok,{'memberRole':role,'dateOfBirth':'1995-05-01','country':'NG','topicIds':T[:3]})
call('PATCH','/me',ada,{'headline':'Building solar irrigation','openToCollaborate':True})
me=call('GET','/me',ada)
check(me['onboardingComplete'] and len(me['interests'])==3, "me['onboardingComplete'] and len(me['interests'])==3")
call('GET','/me/settings',ada); call('PATCH','/me/settings',ada,{'theme':'dark'})
check(call('GET','/me/username-available?username=adaobi_new',ada)['available'], 'username available')

# social
call('POST',f'/users/{ada_id}/follow',tunde); call('POST',f'/users/{ada_id}/follow',tunde)
call('GET','/users/suggested',chi)
prof=call('GET',f"/users/by-username/{me['username']}",tunde)
check(prof['isFollowing'] and prof['followerCount']==1, "prof['isFollowing'] and prof['followerCount']==1")
call('GET',f'/users/{ada_id}/followers',ada)

# posts
p=call('POST','/posts',ada,{'body':'Field test of our solar pump in Kano went well','topicIds':T[:1]},expect=201)
fp=call('POST','/posts',ada,{'body':'followers only','audience':'followers'},expect=201)
lk=call('POST',f"/posts/{p['id']}/like",tunde)
check(lk['likeCount']==1, "lk['likeCount']==1")
c=call('POST',f"/posts/{p['id']}/comments",tunde,{'body':'Great work! What flow rate?'},expect=201)
call('POST',f"/posts/{p['id']}/comments",ada,{'body':'About 2,000 L/h','parentId':c['id']},expect=201)
call('POST',f"/comments/{c['id']}/like",ada)
cm=call('GET',f"/posts/{p['id']}/comments",chi)
check(cm['data'][0]['replyCount']==1, "cm['data'][0]['replyCount']==1")
call('GET',f"/comments/{c['id']}/replies",chi)
call('POST',f"/posts/{p['id']}/share",chi)
f1=call('GET','/feed?tab=following',tunde)
check(len(f1['data'])==2, "len(f1['data'])==2")
f2=call('GET','/feed?tab=for-you',chi)
check(all(x['id']!=fp['id'] for x in f2['data']), 'followers-only leaked')
call('GET',f"/posts/{fp['id']}",chi,expect=404)
call('PATCH',f"/posts/{p['id']}",tunde,{'body':'hack'},expect=403)
call('GET','/feed?limit=1',ada)

# forums
f=call('POST','/forums',ada,{'name':'AgriTech Nigeria','about':'Farm tech builders','topicIds':T[9:10]},expect=201)
call('POST',f"/forums/{f['id']}/join",tunde)
call('POST','/posts',tunde,{'body':'Anyone testing soil sensors?','forumId':f['id']},expect=201)
call('GET','/feed?tab=forums',tunde)
fl=call('GET',f"/forums/{f['id']}",chi)
check(fl['memberCount']==2, "fl['memberCount']==2")
call('GET','/forums?tab=discover',chi); call('GET',f"/forums/{f['id']}/posts",chi); call('GET',f"/forums/{f['id']}/members",chi)
call('DELETE',f"/forums/{f['id']}/join",ada,expect=400)

# search
s=call('GET','/search?q=solar',chi); print('  search hits people/posts:',len(s['people']),len(s['posts']))
call('GET','/search/recent',chi); call('GET','/trending/topics',chi); call('GET','/trending/forums',chi)

# projects + workspace
pr=call('POST','/projects',ada,{'title':'Solar Irrigation Kit','pitch':'Affordable solar pumps','topicIds':T[9:11]},expect=201)
P=pr['id']
jr=call('POST',f'/projects/{P}/join-requests',tunde,{'message':'I build IoT sensors'},expect=201)
call('POST',f'/projects/{P}/join-requests',tunde,{},expect=409)
call('GET',f'/projects/{P}/research',tunde,expect=403)
call('GET',f'/projects/{P}/join-requests',ada)
call('POST',f"/projects/{P}/join-requests/{jr['id']}/accept",ada,{})
jr2=call('POST',f'/projects/{P}/join-requests',chi,{},expect=201)
call('POST',f"/projects/{P}/join-requests/{jr2['id']}/accept",ada,{'role':'viewer'})
pd=call('GET',f'/projects/{P}',tunde)
check(pd['myRole']=='contributor' and pd['memberCount']==3, "pd['myRole']=='contributor' and pd['memberCount']==3")
rd=call('POST',f'/projects/{P}/research',tunde,{'kind':'written','title':'Pump flow analysis','content':{'type':'doc'}},expect=201)
call('POST',f'/projects/{P}/research',chi,{'kind':'written','title':'Viewer attempt','content':{}},expect=403)
call('POST',f'/projects/{P}/workspace-comments',chi,{'targetType':'research_doc','targetId':rd['id'],'body':'Add dry-season data'},expect=201)
call('GET',f"/projects/{P}/workspace-comments?targetType=research_doc&targetId={rd['id']}",ada)
ev=call('POST',f'/projects/{P}/evaluations',chi,{'feasibility':4,'sustainability':5,'novelty':3,'feedback':'Strong field data, needs cost model.','researchDocId':rd['id']},expect=201)
call('POST',f'/projects/{P}/evaluations',tunde,{'feasibility':4,'sustainability':5,'novelty':3,'feedback':'I am not an expert here'},expect=403)
es=call('GET',f'/projects/{P}/evaluations',ada); print('  eval avg:',es['summary'])
proto=call('POST',f'/projects/{P}/prototypes',tunde,{'name':'Pump controller'},expect=201)
call('GET',f"/projects/{P}/prototypes/{proto['id']}",ada)
t=call('POST',f'/projects/{P}/tasks',ada,{'title':'Draft field-test plan','assigneeId':tunde_id,'dueDate':'2026-10-01'},expect=201)
td=call('PATCH',f"/projects/{P}/tasks/{t['id']}",tunde,{'status':'done'})
check(td['status']=='done' and td['completedAt'], "td['status']=='done' and td['completedAt']")
call('POST',f'/projects/{P}/tasks',ada,{'title':'x','assigneeId':'00000000-0000-7000-8000-000000000000'},expect=400)
lg=call('GET',f'/projects/{P}/ledger',ada); print('  ledger:',[e['type'] for e in lg['data']])
call('PUT',f'/projects/{P}/notification-settings',tunde,{'tasks':False})
call('GET',f'/projects/{P}/members',chi); call('GET','/projects?tab=joined',tunde); call('GET',f'/users/{ada_id}/projects',chi)

# chat
pc=call('GET','/conversations?filter=project',tunde)
check(pc['data'][0]['id']==pd['conversationId'], "pc['data'][0]['id']==pd['conversationId']")
m1=call('POST',f"/conversations/{pd['conversationId']}/messages",tunde,{'body':'Kickoff call Monday?'},expect=201)
dm=call('POST','/conversations/direct',tunde,{'userId':ada_id})
dm2=call('POST','/conversations/direct',ada,{'userId':tunde_id})
check(dm['id']==dm2['id'], "dm['id']==dm2['id']")
call('POST',f"/conversations/{dm['id']}/messages",tunde,{'body':'Hi Ada'},expect=201)
r=call('POST',f"/conversations/{dm['id']}/messages",ada,{'body':'Hey!','replyToId':m1['id']},expect=404)
call('GET','/conversations/unread-count',ada)
ms=call('GET',f"/conversations/{dm['id']}/messages",ada)
check(ms['data'][0]['body']=='Hi Ada', "ms['data'][0]['body']=='Hi Ada'")
call('POST',f"/conversations/{dm['id']}/read",ada)
check(call('GET','/conversations/unread-count',ada)['count']==1, 'project chat still unread')
call('GET',f"/conversations/{dm['id']}/messages",chi,expect=404)
call('POST',f"/conversations/{dm['id']}/mute",ada,{'until':None})

# notifications
n=call('GET','/notifications',ada); print('  ada notifications:',[x['type'] for x in n['data']])
call('POST','/notifications/read',ada,{'all':True})
check(call('GET','/notifications/unread-count',ada)['count']==0, "call('GET','/notifications/unread-count',ada)['count']==0")
call('POST','/push-tokens',ada,{'token':'ExponentPushToken[abc123xyz]','platform':'ios'})

# admin + explore + reports
adm=call('POST','/auth/admin/login',body={'email':'admin@communiti.app','password':'Admin12345'},client='admin')['accessToken']
call('GET','/admin/stats/overview',ada,expect=403)
print('  overview:',call('GET','/admin/stats/overview',adm))
call('GET','/admin/stats/user-activity?period=7d',adm)
e=call('POST','/admin/events',adm,{'title':'Lagos Innovation Meetup','category':'meetup','startsAt':'2026-10-02T17:00:00+01:00','endsAt':'2026-10-02T20:00:00+01:00','city':'Lagos','status':'published'},expect=201)
call('POST','/admin/events',adm,{'title':'Bad times','startsAt':'2026-10-02T17:00:00Z','endsAt':'2026-10-01T17:00:00Z'},expect=400)
call('PATCH',f"/admin/events/{e['id']}",adm,{'capacity':100})
rs=call('PUT',f"/events/{e['id']}/rsvp",tunde,{'status':'going'})
check(rs['goingCount']==1 and rs['myRsvp']=='going', "rs['goingCount']==1 and rs['myRsvp']=='going'")
call('PUT',f"/events/{e['id']}/rsvp",tunde,{'status':'interested'})
ee=call('GET',f"/events/{e['id']}",ada)
check(ee['goingCount']==0 and ee['interestedCount']==1, "ee['goingCount']==0 and ee['interestedCount']==1")
call('GET','/events?when=upcoming',ada)
call('POST','/admin/featured',adm,{'title':'Solar Irrigation Kit','projectId':P,'publish':True},expect=201)
check(len(call('GET','/featured',ada)['data'])==1, "len(call('GET','/featured',ada)['data'])==1")
call('GET','/highlights',ada)
rp=call('POST','/reports',chi,{'targetType':'post','targetId':p['id'],'reason':'spam'},expect=201)
call('POST','/reports',ada,{'targetType':'post','targetId':p['id'],'reason':'spam'},expect=400)
q=call('GET','/admin/reports',adm)
check(q['total']==1 and q['data'][0]['preview'], "q['total']==1 and q['data'][0]['preview']")
call('POST',f"/admin/reports/{rp['id']}/action",adm,{'action':'remove_content','note':'Duplicate promo'})
call('GET',f"/posts/{p['id']}",chi,expect=404)
call('POST',f"/admin/content/post/{p['id']}/restore",adm,{})
call('GET',f"/posts/{p['id']}",chi)
call('POST',f'/admin/users/{chi_id}/status',adm,{'action':'suspend','reason':'Test','durationDays':3})
call('GET','/me',chi,expect=401)  # suspended: sessions revoked immediately
call('POST','/auth/login',body={'email':'chioma@example.com','password':'Secret123'},expect=403)
call('POST',f'/admin/users/{chi_id}/status',adm,{'action':'reinstate'})
call('POST','/auth/login',body={'email':'chioma@example.com','password':'Secret123'})
u=call('GET','/admin/users?q=chioma',adm); print('  admin user:',u['data'][0]['status'],u['total'])
call('GET',f'/admin/users/{chi_id}',adm)
b=call('POST','/admin/broadcasts',adm,{'title':'Cohort 3 is open','body':'Apply by 30 Oct','audience':{'memberRoles':['innovator','researcher']}},expect=201)
print('  broadcast recipients:',b['recipientCount'])
call('GET','/admin/audit-logs?action=user.',adm)
call('GET','/admin/content/posts',adm); call('GET','/admin/forums',adm); call('GET','/admin/projects',adm)
call('GET','/internal/cron/cleanup',expect=401)
# regression: PATCH must not reset unspecified fields
call('PATCH',f'/projects/{P}',ada,{'status':'ongoing'})
pp=call('GET',f'/projects/{P}',ada)
check(pp['pitch']=='Affordable solar pumps' and len(pp['topics'])==2 and pp['status']=='ongoing', 'PATCH project keeps unspecified fields')
call('PATCH',f"/forums/{f['id']}",ada,{'about':'Updated'})
ff=call('GET',f"/forums/{f['id']}",ada)
check(len(ff['topics'])==1 and ff['visibility']=='public', "len(ff['topics'])==1 and ff['visibility']=='public'")
