/**
 * Composes the ONE migration file for the whole system:
 *   drizzle-kit DDL (from src/db/schema)  +  src/db/sql/custom.sql
 * Output: supabase/migrations/20260924000000_init.sql
 *
 *   npm run db:generate   # regenerate DDL after schema changes (pre-launch)
 *   npm run db:build      # rebuild the single migration file
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const drizzleDir = join(root, 'drizzle');
const ddlFile = readdirSync(drizzleDir).find((f) => f.endsWith('.sql'));
if (!ddlFile) throw new Error('No drizzle DDL found. Run `npm run db:generate` first.');

const header = `-- ═══════════════════════════════════════════════════════════════════════════
-- CommUniti — complete database schema (single migration)
-- Target: Supabase Postgres 15+ (also runs on plain Postgres 15+)
-- Generated by scripts/build-migration.ts — edit src/db/schema/* and
-- src/db/sql/custom.sql, then run \`npm run db:build\`.
-- ═══════════════════════════════════════════════════════════════════════════

-- Part 1 — tables, enums, keys and indexes (generated from src/db/schema)

`;
const ddl = readFileSync(join(drizzleDir, ddlFile), 'utf8').trim();
const custom = readFileSync(join(root, 'src/db/sql/custom.sql'), 'utf8').trim();

mkdirSync(join(root, 'supabase/migrations'), { recursive: true });
const out = join(root, 'supabase/migrations/20260924000000_init.sql');
writeFileSync(out, `${header}${ddl}\n--> statement-breakpoint\n\n${custom}\n`);
console.log(`Wrote ${out}`);
